version: 0.2

phases:
  pre_build:
    commands:
      - echo Build starts on `date`
  build:
    commands:
      - npm install
  post_build:
    commands:
      - mkdir dist
      - cp index.js dist
      - zip –X –r dist.zip dist/**/*
      - aws lambda update-function-code --function-name codebuild-cli-deploy --zip-file fileb://dist.zip
