version: 0.2

phases:
  pre_build:
    commands:
      - echo Build starts on `date`
  build:
    commands:
      - npm install
  post_build:
    commands:
      - zip dist.zip index.js
      - aws lambda update-function-code --function-name codebuild-cli-deploy --zip-file fileb://dist.zip
